name: Deploy site with frontend and Jekyll

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build frontend first
      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # Build Jekyll site
      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build -d _site

      # Copy frontend dist into Jekyll site folder (_site/frontend)
      - name: Copy frontend build into Jekyll site
        run: |
          mkdir -p _site/frontend
          cp -r frontend/dist/* _site/frontend/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Download Pages artifact
        uses: actions/download-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
